from collections.abc import Iterator, Sequence
from collections.abc import Set as AbstractSet
from typing import ClassVar, SupportsIndex, overload

import numpy as np
from numpy.typing import NDArray
from typing_extensions import Buffer

__version__: str
NO_NEIGHBOR: int
NO_VERTEX: int

# pybind11 enums; not an actual base class at runtime
class _Enum:
    def __init__(self, value: SupportsIndex) -> None: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def value(self) -> int: ...

class VertexInsertionOrder(_Enum):
    AUTO: ClassVar[VertexInsertionOrder]
    AS_PROVIDED: ClassVar[VertexInsertionOrder]
    __members__: ClassVar[dict[str, VertexInsertionOrder]]

class IntersectingConstraintEdges(_Enum):
    NOT_ALLOWED: ClassVar[IntersectingConstraintEdges]
    TRY_RESOLVE: ClassVar[IntersectingConstraintEdges]
    DONT_CHECK: ClassVar[IntersectingConstraintEdges]
    __members__: ClassVar[dict[str, IntersectingConstraintEdges]]

class RefinementCriterion(_Enum):
    SMALLEST_ANGLE: ClassVar[RefinementCriterion]
    LARGEST_AREA: ClassVar[RefinementCriterion]
    __members__: ClassVar[dict[str, RefinementCriterion]]

class Unrefined:
    @property
    def short_edge_triangles(self) -> int: ...
    @property
    def circumcenter_outside(self) -> int: ...
    @property
    def circumcenter_on_vertex(self) -> int: ...
    @property
    def sharp_fixed_corner(self) -> int: ...
    @property
    def short_edges(self) -> int: ...
    @property
    def split_vertex_invalid(self) -> int: ...

class V2d:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    x: float
    y: float
    @overload
    def __init__(self, x: float, y: float) -> None: ...
    @overload
    def __init__(self, buffer: Buffer, /) -> None: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...

class Triangle:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @property
    def vertices(self) -> list[int]: ...
    @vertices.setter
    def vertices(self, value: Sequence[int]) -> None: ...
    @property
    def neighbors(self) -> list[int]: ...
    @neighbors.setter
    def neighbors(self, value: Sequence[int]) -> None: ...

class Edge:
    @overload
    def __init__(self, index_vert_a: int, index_vert_b: int) -> None: ...
    @overload
    def __init__(self, buffer: Buffer, /) -> None: ...
    def __buffer__(self, flags: int, /) -> memoryview: ...
    @property
    def v1(self) -> int: ...
    @property
    def v2(self) -> int: ...
    def __lt__(self, other: Edge) -> bool: ...

class Triangulation:
    def __init__(
        self,
        vertex_insertion_order: VertexInsertionOrder,
        intersecting_edges_strategy: IntersectingConstraintEdges,
        min_dist_to_constraint_edge: float,
    ) -> None: ...
    @property
    def vertices(self) -> list[V2d]: ...
    @property
    def triangles(self) -> list[Triangle]: ...
    @property
    def fixed_edges(self) -> set[Edge]: ...
    @property
    def overlap_count(self) -> dict[Edge, int]: ...
    @property
    def piece_to_originals(self) -> dict[Edge, list[Edge]]: ...
    def vertices_count(self) -> int: ...
    def triangles_count(self) -> int: ...
    def fixed_edges_count(self) -> int: ...
    def overlap_count_count(self) -> int: ...
    def piece_to_originals_count(self) -> int: ...
    def vertices_iter(self) -> Iterator[V2d]: ...
    def triangles_iter(self) -> Iterator[Triangle]: ...
    def fixed_edges_iter(self) -> Iterator[Edge]: ...
    def overlap_count_iter(self) -> Iterator[tuple[Edge, int]]: ...
    def piece_to_originals_iter(self) -> Iterator[tuple[Edge, list[Edge]]]: ...
    def vertices_array(self, *, copy: bool = True) -> NDArray[np.void]: ...
    def triangles_array(self, *, copy: bool = True) -> NDArray[np.void]: ...
    @overload
    def insert_vertices(self, vertices: Sequence[V2d]) -> None: ...
    @overload
    def insert_vertices(self, vertex_buffer: Buffer) -> None: ...
    @overload
    def insert_edges(self, edges: Sequence[Edge]) -> None: ...
    @overload
    def insert_edges(self, edge_buffer: Buffer) -> None: ...
    @overload
    def conform_to_edges(self, edges: Sequence[Edge]) -> None: ...
    @overload
    def conform_to_edges(self, edge_buffer: Buffer) -> None: ...
    def refine_triangles(
        self,
        max_vertices_to_insert: int,
        refinement_criterion: RefinementCriterion = ...,
        refinement_threshold: float = ...,
        to_erase: set[int] | None = None,
        min_edge_length: float = ...,
    ) -> Unrefined: ...
    def find_unrefined_triangles(
        self,
        refinement_criterion: RefinementCriterion = ...,
        refinement_threshold: float = ...,
    ) -> list[int]: ...
    def find_encroached_fixed_edges(self) -> list[Edge]: ...
    def calculate_triangle_depths(self) -> list[int]: ...
    def collect_super_triangle(self) -> set[int]: ...
    def collect_outer_triangles(self) -> set[int]: ...
    def collect_outer_triangles_and_holes(self) -> set[int]: ...
    def erase_super_triangle(self) -> None: ...
    def erase_outer_triangles(self) -> None: ...
    def erase_outer_triangles_and_holes(self) -> None: ...
    def remove_triangles(self, triangle_indices: AbstractSet[int]) -> None: ...
    def finalize_triangulation(self, removed_triangles: AbstractSet[int]) -> None: ...
    def is_finalized(self) -> bool: ...

def verify_topology(triangulation: Triangulation) -> bool: ...
def verify_winding(triangulation: Triangulation) -> bool: ...
def area(a: V2d, b: V2d, c: V2d) -> float: ...
def circumcenter(a: V2d, b: V2d, c: V2d) -> V2d: ...
def smallest_angle(a: V2d, b: V2d, c: V2d) -> float: ...
def deg_to_rad(degrees: float) -> float: ...
